version: 2.1
orbs:
  
   gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
     
  Build-Push-Image-Docker:
    description: Build and push image a docker image
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
            - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1 
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1

    
  deploy:
    description: Deploy application
    machine: true
    steps:
     
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: baas-boilerplate-app
          container: baas-boilerplate-app
          image: asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
workflows:
  build_update_deploy:
    jobs:
      
      - Build-Push-Image-Docker
      - deploy:
          requires:
            - Build-Push-Image-Docker

      
