version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
  slack: circleci/slack@4.1
jobs:
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$GOOGLE_PROJECT_ID/web-builder-api:<< pipeline.number >> .
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/web-builder-api:<< pipeline.number >>
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $GOOGLE_CLUSTER_ID
          perform-login: true
      - run:
          name: Set Image
          command: |
            kubectl set image deployment/<app-name> <app-name>=asia.gcr.io/$GOOGLE_PROJECT_ID/<app-name>:<< pipeline.number >> -n viasocket
workflows:
  Build_Deploy:
    jobs:
      - Build-Push-Image-Docker:
          context:
            - <context-name>
