version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
  slack: circleci/slack@4.1
jobs:
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      -run:
      - google-github-actions/auth@v0.4.0
  with:
    token_format: access_token
    workload_identity_provider: constraints/iam.workloadIdentityPoolAwsAccounts
    service_account: socket-stg-327511@appspot.gserviceaccount.com
    create_credentials_file: true
    access_token_lifetime: 3600s
    access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    id_token_include_email: false
  env:
    PROJECT_ID: 
    GAR_LOCATION: us-central1
    GKE_CLUSTER: cluster-1
    GKE_ZONE: us-central1-c
    DEPLOYMENT_NAME: baas-boilerplate-app
    REPOSITORY: samples
    IMAGE: static-site
      - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
  workflow:
    -Build-Push-Image-Docker
      
