version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
  
jobs:
  Build-Push-Image-Docker:
    description: Build and push image to Google Container
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth

      - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
   Deploy-to-GKE:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $GOOGLE_CLUSTER_ID
          perform-login: true

      - add_ssh_keys:
          fingerprints:
            - $GOOGLE_SSH_KEY

  workflows:
  Build_Deploy:
    jobs:
      - Build-Push-Image-Docker:
       - Deploy-to-GKE:
          requires:
            - Build-Push-Image-Docker
      
