
version:2.1
orbs:
google-github-actions/auth@v0.4.0
  with:
    token_format: access_token
   
    
    create_credentials_file: true
    access_token_lifetime: 3600s
    id_token_include_email: false
  env:
    PROJECT_ID: socket-stg-327511
    GAR_LOCATION: asia-south1
    GKE_CLUSTER: task-1
    GKE_ZONE: asia-south1-b
    DEPLOYMENT_NAME: baas-boilerplate-app
    REPOSITORY: pseudo
    IMAGE: baas-boilerplate-app
jobs:

  build-docker-image:
        description:Build a docker image
    steps:
      - checkout
     -gcr/gcr-auth
      - run:
          name: Build an image
          command: |
          docker build -t asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
    google-auth:
         description:google autorisation command
     steps:
       -run:
           name: google authorisation
          command: |
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia.gcr.io

   push-docker-image:
        description:push a docker image
    steps:
      - checkout
      -gcr/gcr-auth
      - run:
          name: push an image
          command: |
          docker push asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
   deploy-service:
    description: Deploy application to Google Kubernetes Engine
    steps:
     description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $GOOGLE_CLUSTER_ID
          perform-login: true

      - add_ssh_keys:
          fingerprints:
            - $GOOGLE_SSH_KEY
      # Make a cluster
      #Make a deployment.yaml file and service.yaml file
      #getting services
      
      - run:
          name:create cluster
          command: |
          gcloud container cluster create baas-boilerplate
          --num nodes 1 \
          --enable-basic-auth \
          --zone asia-south1-a
       -run:
            name:deployment-and-services
            command: |
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml
        -run:
            name:get-service
            command: |
            kubectl get services
      
            
workflows:
  build-workflow:
    jobs:
      - build-docker-image
      -google auth
        required: build-docker-image
      -push-docker-image
      
      -deploy-service
