version: 2.1
orbs:
  node: circleci/node@1.0.1
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    description: Install npm
    machine: true
    steps:
      - checkout
      - node/install
      - node/install-npm
     
  Build-Push-Image-Docker:
    description: Build and push image a docker image
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: baas-boilerplate-app
          tag: "v1" 
      - gcr/push-image:
          image: baas-boilerplate-app
          tag: "v1" 
    
  deploy:
    description: Deploy application
    machine: true
    steps:
     
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: baas-boilerplate-app
          container: baas-boilerplate-app
          image: asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          requires:
            - build
      - deploy:
          requires:
            - Build-Push-Image-Docker
