version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
  slack: circleci/slack@4.1
jobs:
  Build-Push-Image-Docker:
    description: Build and push image to Google Container
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth

      - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$socket-stg-327511/baas-boilerplate-app:v1
  workflows:
  Build_Deploy:
    jobs:
      - Build-Push-Image-Docker:
      
