
version:2.1
jobs:
  build-docker-image:
        description:Build a docker image
    steps:
      - checkout
     
      - run:
          name: Build an image
          command: |
          docker build -t asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
   push-docker-image:
        description:push a docker image
    steps:
      - checkout
      
      - run:
          name: push an image
          command: |
          docker push asia.gcr.io/socket-stg-327511/baas-boilerplate-app:v1
   deploy-service:
    description: Deploy application to Google Kubernetes Engine
    steps:
      # Make a cluster
      #Make a deployment.yaml file and service.yaml file
      #getting service 
      - run:
          name:create cluster
          command: |
          gcloud container cluster create baas-boilerplate
          --num nodes 1 \
          --enable-basic-auth \
          --zone us-central1-a
       -run:
            name:deployment-and-services
            command: |
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml
        -run:
            name:get-service
            command: |
            kubectl get services
      
            
workflows:
  build-workflow:
    jobs:
      - build-docker-image
      -push-docker-image
      -deploy-service
